import type { Metadata } from "next";
import { LegalDoc } from "@/components/public/LegalDoc";
import { SUPPORT_EMAIL } from "@/lib/support";

export const metadata: Metadata = {
  title: "Privacy Policy · The Mini Mainframe",
  description: "How The Mini Mainframe handles your data.",
  alternates: { canonical: "/privacy" },
};

export default function PrivacyPage() {
  return (
    <LegalDoc
      title="PRIVACY POLICY"
      updated="September 2026"
      intro="The Mini Mainframe is a hobby paint-and-miniature management tool. This policy explains what we collect, why, and the choices you have. We aim to collect as little as possible."
      sections={[
        {
          heading: "What we collect",
          body: (
            <ul className="list-disc space-y-1 pl-5">
              <li>Account: your username and a password (stored only as a salted hash), plus an optional recovery email.</li>
              <li>Your content: projects, recipes, paint inventory, collection items, sessions, and events you create.</li>
              <li>Billing: if you sponsor the Mainframe, Stripe processes your payment; we store your Stripe customer id and plan status, never your card details.</li>
              <li>Basic technical logs needed to run and secure the service.</li>
            </ul>
          ),
        },
        {
          heading: "How we use it",
          body: "To provide the app, authenticate you, process payments, send account emails (e.g. password resets), and keep the service secure. Some optional features send the input you provide to the AI subprocessors listed below. We do not sell your data.",
        },
        {
          heading: "Third parties (subprocessors)",
          body: (
            <>
              <p className="mb-2">
                We share data with the following subprocessors, each only to
                provide their part of the service:
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>Vercel — hosting, and Vercel Analytics for privacy-friendly, aggregate usage metrics.</li>
                <li>Sentry — error monitoring: when the app hits an error we send Sentry a diagnostic report (error details and basic request context) so we can diagnose and fix it.</li>
                <li>Our database provider — stores your account and content.</li>
                <li>Stripe — payments (if you sponsor).</li>
                <li>An email provider — transactional email (e.g. password resets, verification).</li>
                <li>Anthropic — powers our AI features: the prompts you send to the AI recipe creator, and the images you submit to the public gallery (which are checked by automated moderation).</li>
                <li>Groq — parses the army-list text you upload when importing a list.</li>
              </ul>
              <p className="mt-2">
                Each processes data only to provide their service. The AI
                subprocessors (Anthropic, Groq) receive data only when you use
                the optional feature that relies on them.
              </p>
            </>
          ),
        },
        {
          // Required by the Chrome Web Store review: the policy linked from a
          // listing has to cover what the EXTENSION itself handles, not just
          // the web app. Keep this in sync with extension/STORE_LISTING.md's
          // data-handling disclosures.
          heading: "Browser extension",
          body: (
            <>
              <p className="mb-2">
                The optional{" "}
                <span className="text-cyan-lite">Mini Mainframe Collection</span>{" "}
                browser extension adds the product page you&apos;re viewing to
                your collection. It handles two pieces of data, both only
                because you asked it to:
              </p>
              <ul className="list-disc space-y-1 pl-5">
                <li>
                  <strong>Your extension token.</strong> Generated by you in
                  Settings and stored in your browser&apos;s extension storage.
                  It is sent to us only as an <code>Authorization</code> header
                  so we know which account to add the item to. The token is a
                  signed value derived from your account id — we keep no copy of
                  it, and regenerating it in Settings immediately invalidates the
                  old one everywhere it&apos;s pasted.
                </li>
                <li>
                  <strong>The product page URL.</strong> Sent to us only at the
                  moment you click the extension button, so we can read the
                  product details and save the item. We do not read, collect, or
                  monitor your browsing in the background — the extension has no
                  access to any page until you open it, and it holds no history.
                </li>
              </ul>
              <p className="mt-2">
                The extension talks to no server other than The Mini Mainframe.
                Neither the token nor the URLs are sold, shared with third
                parties, or used for advertising. Uninstalling the extension
                removes the stored token from your browser; you can also revoke
                it any time from Settings.
              </p>
            </>
          ),
        },
        {
          heading: "Your choices",
          body: "You can export all of your data from Settings at any time, and you can delete your account to remove your content. Email us to exercise any data rights.",
        },
        {
          heading: "Contact",
          body: (
            <>
              Questions about privacy, or want to exercise a data right? Email us
              at{" "}
              <a href={`mailto:${SUPPORT_EMAIL}`} className="text-cyan-lite underline">
                {SUPPORT_EMAIL}
              </a>
              .
            </>
          ),
        },
      ]}
    />
  );
}
