/**
 * Shared paint catalog types. Single source of truth — every downstream
 * component (table row, detail panel, slot picker, filters) imports from
 * here so a schema change ripples in one direction.
 *
 * The paint catalog lives as a static JSON artifact under
 * `app/public/data/paints.json`, generated by `scripts/export-paints.ts`
 * from the canonical Webscraper SQLite database.
 */

/**
 * Paint product types. Mirrors the Webscraper `paints.type` column with
 * normalisation: blank/null → "Paint"; Enamel/Oil → "Paint"; Medium → "Effect".
 * Ink and Lacquer are reserved for future scraped sources — no rows use them
 * today but the union is forward-compatible.
 */
export const paintTypes = [
  "Paint",
  "Wash",
  "Metallic",
  "Contrast",
  "Air",
  "Primer",
  "Varnish",
  "Pigment",
  "Effect",
  "Ink",
  "Lacquer",
] as const;
export type PaintType = (typeof paintTypes)[number];

/**
 * Hex-confidence buckets surfaced as a green/amber/grey dot beside the
 * swatch. Derived from `hex_source` in the source DB: Stahly hand-painted
 * swatches → high; manufacturer-published → medium; everything else → low.
 */
export const hexConfidenceLevels = ["high", "medium", "low"] as const;
export type HexConfidence = (typeof hexConfidenceLevels)[number];

/**
 * The canonical Paint shape consumed by the client. `line` and `sku` are
 * optional because the source DB doesn't populate them for every brand yet
 * — components must render gracefully when they're missing.
 */
export interface Paint {
  id: string;
  brand: string;
  line?: string;
  name: string;
  sku?: string;
  type: PaintType;
  hex: string;
  hexConfidence: HexConfidence;
  hexSource: string;
  sourceUrl: string;
}

/**
 * The wrapper written by the export script. Includes a millisecond
 * timestamp the Dexie cache uses as a cheap, deterministic cache key.
 */
export interface PaintCatalog {
  __exported_at: number;
  __row_count: number;
  paints: Paint[];
}

/**
 * Filter state shared across the library page. Each field is independent
 * (AND-composed in the page). Empty arrays mean "no filter on this axis".
 */
export interface PaintFilter {
  brands: string[];
  lines: string[];
  types: PaintType[];
  hueBands: string[];
  ownedOnly: boolean;
  hexQuery: string;
  textQuery: string;
}

export const EMPTY_FILTER: PaintFilter = {
  brands: [],
  lines: [],
  types: [],
  hueBands: [],
  ownedOnly: false,
  hexQuery: "",
  textQuery: "",
};
